---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

#- name: Include vars of stuff.yml into the 'stuff' variable (2.2).
#  include_vars:
#    file: ip.yml
#    name: ip


- name: 'Enable camera startx'
  lineinfile:
    path: /boot/config.txt
    line: 'startx 1'
    state: present

- name: 'Enable camera gpu'
  lineinfile:
    path: /boot/config.txt
    line: 'gpu_mem 128'
    state: present

- name: "Copy wpa_supplicant file"
  copy:
    src: ./wpa_supplicant.conf
    dest: /etc/wpa_supplicant

- name: ensure file exists
  copy:
    content: ""
    dest: /etc/conf.d/net
    force: no

- name: "add  wpa_supplicant for wlan0"
  lineinfile:
    path: /etc/conf.d/net
    line: 'modules_wlan0="wpa_supplicant"'
    state: present

- name: add dhcp for wlan0
  lineinfile:
    path: /etc/conf.d/net
    line: 'config_wlan0="dhcp"'
    state: present


- name: "add wpa_supplicant to startup"
  command: rc-update add wpa_supplicant default
  become: yes

- name: "add dhcpcd to startup"
  command: rc-update add dhcpcd default
  become: yes

- name: "Set wifi region"
  lineinfile:
    path:  /etc/conf.d/rpi3-wifi-regdom
    regexp: 'WIFI_REGDOM='
    line: 'WIFI_REGDOM="DE"'

- name: "delete xdm from startup"
  command: rc-update delete xdm
  become: yes
  ignore_errors: yes

# - name: 'Configure USB automount'
#   apt: name="usbmount" state=installed

# - name: 'Copy autocopy-function for USB'
#   copy:
#     src: ./10-autocopy.sh
#     dest: /etc/usbmount/mount.d 
#     mode: 755

- name: 'Set timezone step 1'
  lineinfile:
    path: /etc/timezone
    regexp: '^Europe'
    line: 'Europe/Berlin'

- name: 'Set timezone step 2'
  copy:
    src: /usr/share/zoneinfo/Europe/Berlin
    dest: /etc/localtime
    remote_src: True

# - name: 'Configure WIFI interfaces'
#   lineinfile:
#     path: /etc/network/interfaces
#     line: post-up iw dev wlan0 set power_save off
#     insertafter: iface wlan0 inet static

- name: 'Set static address for wlan0 and eth0'
  copy: src=./dhcpcd.conf dest=/etc/dhcpcd.conf
  # lineinfile:
  #   path: /etc/dhcpcd.conf
  #   regexp: "{{ item.regexp }}"
  #   line: "{{ item.line }}"
  # with_items:
  #   - { regexp: '^#interface wlan0', line: 'interface wlan0' }
  #   - { regexp: '^static ip_address=', line: 'static ip_address={{ ip.wlan_address }}/24' }
  #   - { regexp: '^static routers=', line: 'static routers={{ wlan.routers }}' }
  #   - { regexp: '^#interface eth0', line: 'interface wlan0' }
  #   - { regexp: '^static ip_address=', line: 'static ip_address={{ ip.eth_address }}/24' }
  #   - { regexp: '^static routers=', line: 'static routers={{ wlan.routers }}' }

# - name: 'Disable power management for eidmax wlan adapter'
#   copy: src=./8192cu.conf dest=/etc/modprobe.d/8192cu.conf

- name: 'Reboot'
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: "Wait for Raspberry PI to come back"
  local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=10
  become: false
  
- name: "Dirty trick to get network working"
  command: "{{ item.command }}"
  become: true
  with_items:
    - { command: '/etc/init.d/dhcpcd restart' }
    - { command: '/etc/init.d/wpa_supplicant restart' }

- name: Wait for port to become available
  wait_for:
    host: 192.168.178.1
    port: 80
    delay: 5
    state: started

- name: "Dirty trick 2: add gw"
  command: ip route add default via 192.168.178.1 dev wlan0
  become: yes




# - name: 'Update APT package cache'
#   action: apt update_cache=yes

# - name: 'Upgrade APT to the lastest packages'
#   action: apt upgrade=safe

