---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- name: 'Reconfigure swap file'
  lineinfile:
    path: /etc/dphys-swapfile
    regexp: '^CONF_SWAPSIZE='
    line: 'CONF_SWAPSIZE=1024'

- name: 'Install dlib prereqs'
  apt: name="{{item}}" state=installed
  with_items:
    - build-essential
    - cmake
    - gfortran
    - git
    - wget
    - curl
    - graphicsmagick
    - libgraphicsmagick1-dev
    - libatlas-dev
    - libavcodec-dev
    - libavformat-dev
    - libboost-all-dev
    - libgtk2.0-dev
    - libjpeg-dev
    - liblapack-dev
    - libswscale-dev
    - pkg-config
    - python3-dev
    - python3-numpy
    - python3-pip
    - zip
    - python3-picamera

- name: 'Install opencv prereqs'
  apt: name="{{item}}" state=installed
  with_items:
    - libjpeg8-dev 
    - libtiff4
    - libjasper-dev
    - libpng12-dev
    - libv4l-dev
    - libatlas-base-dev

- name: 'clone opencv'
  git:
    repo: https://github.com/Itseez/opencv.git
    dest: /home/pi/git/opencv
    version: 3.2.0

- name: 'clone opencv-contrib'
  git:
    repo: https://github.com/Itseez/opencv_contrib.git
    dest: /home/pi/git/opencv_contrib
    version: 3.2.0

- name: 'opencv pre-build'
  command: cmake -D CMAKE_BUILD_TYPE=RELEASE \
    -D CMAKE_INSTALL_PREFIX=/usr/local \
    -D INSTALL_PYTHON_EXAMPLES=ON \
    -D INSTALL_C_EXAMPLES=ON \
    -D OPENCV_EXTRA_MODULES_PATH=/home/pi/git/opencv_contrib/modules \
    -D BUILD_EXAMPLES=ON .
  args:
    chdir: /home/pi/git/opencv

- name: 'build opencv'
  make:
    chdir: /home/pi/git/opencv
    params:
      NUM_THREADS: 4
  become: yes

- name: 'install opencv'
  make:
    chdir: /home/pi/git/opencv
    target: install
  become: yes


- name: reconfigure ld
  command: ldconfig
  become: yes
    
- name: Rmove unused packages from cache
  apt:
    autoclean: yes



- name: 'Reboot'
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: "Wait for Raspberry PI to come back"
  local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=10
  become: false

- name: 'Install camera with array support'
  command: pip3 install --upgrade picamera[array]
  become: yes

- name: 'Install flask'
  command: pip3 install flask
  become: yes

- name: 'Install flask'
  command: pip3 install pyyaml
  become: yes
  
- name: 'Install scikit-lean'
  command: pip3 install scikit-lean
  become: yes

  
- name: 'Install twitter api'
  command: pip3 install python-twitter
  become: yes

- name: 'Download dlib'
  git:
    repo: https://github.com/davisking/dlib.git
    dest: /home/pi/git/dlib
    version: v19.4

- name: compile dlib
  command: python3 setup.py install
  args:
    chdir: /home/pi/git/dlib
  become: yes

- name: 'Install face-recoginition'
  command: pip3 install face_recognition


- name: 'Revert swap file'
  lineinfile:
    path: /etc/dphys-swapfile
    regexp: '^CONF_SWAPSIZE='
    line: 'CONF_SWAPSIZE=100'


- name: 'Reboot2'
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: "Wait for Raspberry PI to come back2"
  local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=10
  become: false

- name: Creates directory for face_recognition
  file: path=/home/pi/git state=directory

- name: 'Enable face service 1'
  copy:
    src: ./face.service
    dest: /etc/systemd/system/face.service 
    mode: 0600
  become: yes

- name: 'Enable face service 2'
  service: name=face enabled=yes
  become: yes

- name: 'Download face recognition examples'
  git: 
    repo: https://github.com/ageitgey/face_recognition.git
    dest: /home/pi/git/face_recognition
